apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/te22204/git/KubeFlower/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  storageClassName: manual
  resources:
    requests: 
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  selector:
    matchLabels:
      pv-name: my-pv

