apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv1
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/ubuntu/git/kubeFlower/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc1
spec:
  storageClassName: manual
  resources:
    requests: 
      storage: 1Gi
  accessModes:
    - ReadWriteOnce

