apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: kubeflower
    image: kubeflower:latest
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: my-volume
      mountPath: /usr/data
  volumes:
  - name: my-volume
    persistentVolumeClaim:
      claimName: my-pvc