apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: flower:latest
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: my-volume
      mountPath: /usr/data/flower
  volumes:
  - name: my-volume
    hostPath:
      path: /data/flower
      type: Directory
