apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower-client
  labels:
    app: flower-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flower-client 
  template:
    metadata:
      labels:
        app: flower-client 
    spec:
      containers:
      - name: kubeflower
        image: kubeflower:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args: ["python ./src/client.py --server 'fl-deployment-service-server' --port '30051'"]
        ports:
        - containerPort: 30051
