apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower-client
  labels:
    app: flower-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flower-client 
  template:
    metadata:
      labels:
        app: flower-client 
    spec:
      nodeName: juan-2-mshed-gpu
      containers:
      - name: kubeflower
        image: juanmarcelouob/kubeflower:latest
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args: ["python ./src/client.py --server 'fl-deployment-service-server' --port '30051' --download True"]
        ports:
        - containerPort: 30051
