apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower-client
  labels:
    app: flower-client
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  selector:
    matchLabels:
      app: flower-client
  template:
    metadata:
      labels:
        app: flower-client
    spec:
      affinity:
        # ⬇⬇⬇ This ensures pods will land on separate hosts
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions: [{ key: app, operator: In, values: [flower-client] }]
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: kubeflower
        image: kubeflower:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args: ["python ./src/client.py --server 'service-server' --port '30051'"]
        ports:
        - containerPort: 30051
      terminationGracePeriodSeconds: 1