apiVersion: flwr.dev/v1
kind: FLDeployment
metadata:
  name: fl-deployment
  finalizers:
spec:
  server:
    port: 8080
  client:
    replicas: 5
    port: 30051
    dataset:
      download: true
       
 
