apiVersion: apps/v1
kind: Deployment
metadata:
  name: fl-deployment1
  labels:
    app: flower-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flower-server 
  template:
    metadata:
      labels:
        app: flower-server 
    spec:
      containers:
      - name: flower-server
        image: flower:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args: ["python ./src/server.py"]
        ports:
        - containerPort: 8080
      - name: flower-client
        image: flower:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args: ["python ./src/client.py --server 'service-server' --port '30051'"]
        ports:
        - containerPort: 30051

