apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: fldeployments.flwr.dev
spec:
  group: flwr.dev
  names:
    kind: FLDeployment
    plural: fldeployments
    singular: fldeployment
    shortNames:
    - fl
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                server:
                  type: object
                  properties:
                    image:
                      type: string
                    imagePullPolicy:
                      type: string
                    port:
                      type: integer
                    replicas:
                      type: integer
                    args:
                      type: array
                      items:
                        type: string
                client:
                  type: object
                  properties:
                    image:
                      type: string
                    imagePullPolicy:
                      type: string
                    port:
                      type: integer
                    replicas:
                      type: integer
                    privacy:
                      type: object
                      properties:
                        budget:
                          type: number
                        rate:
                          type: number
                    args:
                      type: array
                      items:
                        type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
